AlignParameters:
  Enabled: false
BracesAroundHashParameters:
  Enabled: false
Documentation:
  Enabled: false
ClassLength:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
EmptyLines:
  Enabled: false
EmptyLinesAroundBody:
  Enabled: false
FileName:
  Enabled: false
HashSyntax:
  Enabled: false
HasAndBelongsToMany:
  Enabled: false
LeadingCommentSpace:
  Enabled: false  
LineLength:
  Enabled: false
NumericLiterals:
  Enabled: false
MethodLength:
  Enabled: false
PercentLiteralDelimiters:
  Enabled: false
RedundantSelf:
  Enabled: false
SignalException:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
StringLiterals:
  Enabled: false
WordArray:
  Enabled: false
Tab:
  Enabled: false
TrailingBlankLines:
  Enabled: false
TrailingWhitespace:
  Enabled: false
Void:
  Enabled: false