development:
  smtp_settings:
    :address: smtp.gmail.com
    :port: 587
    :domain: gmail.com
    :user_name: magazmailer@gmail.com
    :password: QWERTY!@#$%
    :authentication: plain
    :enable_starttls_auto: true
  default:
    :from: magazmailer@gmail.com
    :to: magazmailer@gmail.com

production:
  smtp_settings:
    :address: smtp.gmail.com
    :port: 587
    :domain: gmail.com
    :user_name: magazmailer@gmail.com
    :password: QWERTY!@#$%
    :authentication: plain
    :enable_starttls_auto: true
  default:
    :from: magazmailer@gmail.com
    :to: magazmailer@gmail.com